# Generated by Django 2.0.5 on 2018-05-31 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180531_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apibucketlist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblproductlist',
            options={'managed': True},
        ),
    ]
