# Generated by Django 2.0.5 on 2018-06-01 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180531_1603'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiBucketlist',
        ),
        migrations.DeleteModel(
            name='TblProductlist',
        ),
    ]
