# Generated by Django 2.0.5 on 2019-02-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrDatabaseModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailsName', models.CharField(db_column='detailsName', max_length=255)),
                ('phoneNumber', models.CharField(blank=True, db_column='phoneNumber', max_length=20, null=True)),
                ('contactPerson', models.CharField(blank=True, db_column='contactPerson', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_accountdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountDetailsJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountDetailsID', models.ForeignKey(db_column='accountDetailsID', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountDetails')),
            ],
            options={
                'db_table': 'tbl_accountdetailsjunction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(db_column='accountID', max_length=10)),
                ('accountName', models.CharField(db_column='accountName', max_length=255)),
                ('commonName', models.CharField(db_column='commonName', max_length=255)),
                ('accountDetails', models.ManyToManyField(through='mrAdminOffice.AccountDetailsJunction', to='mrAdminOffice.AccountDetails')),
                ('parentAccountID', models.ForeignKey(blank=True, db_column='parentAccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName')),
                ('productGroup', models.ForeignKey(db_column='productGroup', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productgroupnames')),
                ('route', models.ForeignKey(db_column='route', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes')),
            ],
            options={
                'db_table': 'tbl_accountname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'tbl_checklist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChecklistAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_column='area', max_length=100)),
            ],
            options={
                'db_table': 'tbl_checklistareas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'tbl_dailyreport',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MessageLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(db_column='levelName', max_length=100)),
                ('levelColor', models.CharField(db_column='levelColor', max_length=100)),
                ('levelRank', models.IntegerField(db_column='levelRank')),
                ('report', models.BooleanField(db_column='report', default=False)),
                ('checklist', models.BooleanField(db_column='checklist', default=False)),
            ],
            options={
                'db_table': 'tbl_messagelevels',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountMRid', models.CharField(db_column='accountMRid', max_length=4)),
                ('accountID', models.CharField(db_column='accountID', max_length=40)),
                ('commonName', models.CharField(db_column='commonName', max_length=255)),
                ('orderDate', models.DateField(db_column='orderDate')),
                ('dateCreated', models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True)),
                ('lastModified', models.DateTimeField(auto_now=True, db_column='lastModified', null=True)),
                ('delivered', models.BooleanField(db_column='delivered', default=False)),
                ('accountsid', models.ForeignKey(db_column='accountsid', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName')),
                ('routeid', models.ForeignKey(db_column='routeid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes')),
                ('timeStampid', models.ForeignKey(db_column='timeStampid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.TimeStamp')),
                ('userid', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_orderdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderProductAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productMRid', models.CharField(db_column='productMRid', max_length=20)),
                ('amount', models.IntegerField(db_column='amount')),
                ('status', models.BooleanField(db_column='status', default=False)),
                ('lastModified', models.DateTimeField(auto_now=True, db_column='lastModified', null=True)),
                ('orderDetailsid', models.ForeignKey(db_column='orderDetailsid', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.OrderDetails')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_orderproductamounts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReportImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='dailyReport/')),
                ('report', models.ForeignKey(db_column='report', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.DailyReport')),
            ],
            options={
                'db_table': 'tbl_reportimages',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='messageLevel',
            field=models.ForeignKey(db_column='messageLevel', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.MessageLevels'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='reply',
            field=models.ForeignKey(blank=True, db_column='reply', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.DailyReport'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='timeStampID',
            field=models.ForeignKey(db_column='timeStampID', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.TimeStamp'),
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklist',
            name='area',
            field=models.ForeignKey(db_column='area', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.ChecklistAreas'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='importance',
            field=models.ForeignKey(db_column='importance', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mrAdminOffice.MessageLevels'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='timeStampID',
            field=models.ForeignKey(db_column='timeStampID', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.TimeStamp'),
        ),
        migrations.AddField(
            model_name='checklist',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountdetailsjunction',
            name='accountID',
            field=models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
        ),
    ]
