# Generated by Django 2.0.5 on 2018-11-21 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mrDatabaseModels', '0030_auto_20181121_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(db_column='accountID', max_length=10, unique=True)),
                ('accountName', models.CharField(db_column='accountName', max_length=255)),
                ('commonName', models.CharField(db_column='commonName', max_length=255)),
            ],
            options={
                'db_table': 'tbl_accountname',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('accountid', models.OneToOneField(db_column='accountid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mrAdminOffice.AccountName')),
                ('phoneNumber1', models.CharField(blank=True, db_column='phoneNumber1', max_length=15, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_accountdetails',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accountname',
            name='route',
            field=models.ForeignKey(db_column='weekDay', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes'),
        ),
    ]
