# Generated by Django 2.0.5 on 2018-11-21 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGroupName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(db_column='groupName', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'tbl_productgroupname',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='accountdetails',
            name='accountid',
        ),
        migrations.AlterField(
            model_name='accountname',
            name='route',
            field=models.ForeignKey(db_column='route', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes'),
        ),
        migrations.DeleteModel(
            name='AccountDetails',
        ),
        migrations.AddField(
            model_name='accountname',
            name='productGroup',
            field=models.ForeignKey(db_column='productGroup', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.ProductGroupName'),
        ),
    ]
