# Generated by Django 2.0.5 on 2018-11-21 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0030_auto_20181121_0851'),
        ('mrAdminOffice', '0002_auto_20181121_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('childAccountID', models.CharField(db_column='ChildAccountID', max_length=20)),
                ('accountName', models.CharField(db_column='accountName', max_length=255)),
            ],
            options={
                'db_table': 'tbl_accountchild',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountGrandChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grandChildAccountID', models.CharField(db_column='grandChildAccountID', max_length=50)),
                ('accountName', models.CharField(db_column='accountName', max_length=255)),
                ('childAccount', models.ForeignKey(db_column='childAccount', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountChild')),
                ('productGroup', models.ForeignKey(db_column='productGroup', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.ProductGroupName')),
                ('route', models.ForeignKey(db_column='route', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes')),
            ],
            options={
                'db_table': 'tbl_accountgrandchild',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='accountname',
            name='productGroup',
        ),
        migrations.RemoveField(
            model_name='accountname',
            name='route',
        ),
        migrations.AddField(
            model_name='accountchild',
            name='mainAccount',
            field=models.ForeignKey(db_column='mainAccount', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
        ),
    ]
