# Generated by Django 2.0.5 on 2019-02-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0002_remove_orderdetails_accountsid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='accountsid',
            field=models.ForeignKey(db_column='accountsid', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
            preserve_default=False,
        ),
    ]
