# Generated by Django 2.0.5 on 2018-11-21 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0003_auto_20181121_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgrandchild',
            name='productGroup',
            field=models.ForeignKey(db_column='productGroup', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productgroupnames'),
        ),
        migrations.DeleteModel(
            name='ProductGroupName',
        ),
    ]
