# Generated by Django 2.0.5 on 2019-02-25 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0001_initial'),
        ('mrAdminOffice', '0004_remove_orderdetails_routeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='routeid',
            field=models.ForeignKey(db_column='routeid', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes'),
            preserve_default=False,
        ),
    ]
