# Generated by Django 2.0.5 on 2018-12-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0004_auto_20181121_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.CharField(db_column='LevelName', max_length=100)),
                ('levelColor', models.CharField(db_column='LevelColor', max_length=100)),
            ],
            options={
                'db_table': 'tbl_messagelevels',
                'managed': True,
            },
        ),
    ]
