# Generated by Django 2.0.5 on 2018-12-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrAdminOffice', '0005_messagelevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(db_column='message')),
                ('messageLevel', models.ForeignKey(db_column='messageLevel', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.MessageLevels')),
                ('user', models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_dailyreport',
                'managed': True,
            },
        ),
    ]
