# Generated by Django 2.0.5 on 2019-02-25 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrAdminOffice', '0005_orderdetails_routeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproductamounts',
            name='user',
        ),
        migrations.AddField(
            model_name='orderproductamounts',
            name='userid',
            field=models.ForeignKey(db_column='userid', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
