# Generated by Django 2.0.5 on 2019-05-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0006_auto_20190225_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='accountsid',
            field=models.ForeignKey(db_column='accountids', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
        ),
    ]
