# Generated by Django 2.0.5 on 2018-12-04 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0006_dailyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='messagelevels',
            name='levelRank',
            field=models.IntegerField(db_column='levelRank', default=1),
            preserve_default=False,
        ),
    ]
