# Generated by Django 2.0.5 on 2018-12-05 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0032_stocktakingtimes_selectivedelete'),
        ('mrAdminOffice', '0007_auto_20181204_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='timeStampID',
            field=models.ForeignKey(db_column='timeStampID', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.TimeStamp'),
        ),
        migrations.AlterField(
            model_name='messagelevels',
            name='levelColor',
            field=models.CharField(db_column='levelColor', max_length=100),
        ),
        migrations.AlterField(
            model_name='messagelevels',
            name='levelName',
            field=models.CharField(db_column='levelName', max_length=100),
        ),
    ]
