# Generated by Django 2.0.5 on 2018-12-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0008_auto_20181205_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(db_column='area', max_length=100)),
            ],
            options={
                'db_table': 'tbl_checklistareas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='messagelevels',
            name='catagory',
            field=models.CharField(db_column='catagory', default=1, max_length=100),
            preserve_default=False,
        ),
    ]
