# Generated by Django 2.0.5 on 2018-12-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0009_auto_20181219_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagelevels',
            name='catagory',
        ),
        migrations.AddField(
            model_name='messagelevels',
            name='checklist',
            field=models.BooleanField(db_column='checklist', default=False),
        ),
        migrations.AddField(
            model_name='messagelevels',
            name='report',
            field=models.BooleanField(db_column='report', default=False),
        ),
    ]
