# Generated by Django 2.0.5 on 2019-07-10 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0009_orderdetails_accountaccessdbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='accountAccessDBid',
        ),
    ]
