# Generated by Django 2.0.5 on 2019-07-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0010_remove_orderdetails_accountaccessdbid'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountname',
            name='accountAccessDBid',
            field=models.IntegerField(db_column='accountAccessDBid', null=True, unique=True),
        ),
    ]
