# Generated by Django 2.0.5 on 2018-12-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0011_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='reply',
            field=models.ForeignKey(blank=True, db_column='reply', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.DailyReport'),
        ),
    ]
