# Generated by Django 2.0.5 on 2019-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0011_accountname_accountaccessdbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountname',
            name='accountAccessDBid',
            field=models.IntegerField(db_column='accountAccessDBid', null=True),
        ),
    ]
