# Generated by Django 2.0.5 on 2019-08-30 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0012_auto_20190710_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetails',
            name='accountsid',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='routeid',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='timeStampid',
        ),
        migrations.RemoveField(
            model_name='orderdetails',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='orderproductamounts',
            name='orderDetailsid',
        ),
        migrations.RemoveField(
            model_name='orderproductamounts',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='orderproductamounts',
            name='userid',
        ),
        migrations.DeleteModel(
            name='OrderDetails',
        ),
        migrations.DeleteModel(
            name='OrderProductAmounts',
        ),
    ]
