# Generated by Django 2.0.5 on 2019-01-02 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0032_stocktakingtimes_selectivedelete'),
        ('mrAdminOffice', '0013_auto_20190102_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detailsName', models.CharField(db_column='detailsName', max_length=255)),
                ('phoneNumber', models.CharField(blank=True, db_column='phoneNumber', max_length=20, null=True)),
                ('contactPerson', models.CharField(blank=True, db_column='contactPerson', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='address', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_accountdetails',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountDetailsJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountDetailsID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountDetails')),
            ],
            options={
                'db_table': 'tbl_accountdetailsjunction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AccountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountID', models.CharField(db_column='accountID', max_length=10, unique=True)),
                ('accountName', models.CharField(db_column='accountName', max_length=255)),
                ('commonName', models.CharField(db_column='commonName', max_length=255)),
                ('accountDetails', models.ManyToManyField(through='mrAdminOffice.AccountDetailsJunction', to='mrAdminOffice.AccountDetails')),
                ('parentAccountID', models.ForeignKey(blank=True, db_column='parentAccountID', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName')),
                ('productGroup', models.ForeignKey(db_column='productGroup', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productgroupnames')),
                ('route', models.ForeignKey(db_column='route', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DeliveryRoutes')),
            ],
            options={
                'db_table': 'tbl_accountname',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='accountdetailsjunction',
            name='accountID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
        ),
    ]
