# Generated by Django 2.0.5 on 2019-01-02 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrAdminOffice', '0014_auto_20190102_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetailsjunction',
            name='accountDetailsID',
            field=models.ForeignKey(db_column='accountDetailsID', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountDetails'),
        ),
        migrations.AlterField(
            model_name='accountdetailsjunction',
            name='accountID',
            field=models.ForeignKey(db_column='accountID', on_delete=django.db.models.deletion.CASCADE, to='mrAdminOffice.AccountName'),
        ),
    ]
