# Generated by Django 2.0.5 on 2018-06-01 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batchgroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchname', models.CharField(db_column='batchName', max_length=255, unique=True)),
                ('ranking', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'tbl_batchgroups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(db_column='productID', max_length=20, unique=True)),
                ('proddescription', models.CharField(blank=True, db_column='prodDescription', max_length=255, null=True)),
                ('packaging', models.IntegerField(blank=True, null=True)),
                ('unitweight', models.FloatField(blank=True, db_column='unitWeight', null=True)),
                ('packageweight', models.FloatField(blank=True, db_column='packageWeight', null=True)),
                ('productonhold', models.IntegerField(blank=True, db_column='productOnHold', null=True)),
                ('batchranking', models.IntegerField(blank=True, db_column='batchRanking', null=True)),
                ('batchgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Batchgroups')),
            ],
            options={
                'db_table': 'tbl_productlist',
                'managed': True,
            },
        ),
    ]
