# Generated by Django 2.0.5 on 2019-02-28 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='rankingInGroup',
            field=models.IntegerField(blank=True, db_column='rankingInGroup', null=True),
        ),
    ]
