# Generated by Django 2.0.5 on 2018-06-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packagingType', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_packaging',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TblDeliveryroutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routes', models.CharField(max_length=255, unique=True)),
                ('loadingday', models.IntegerField(blank=True, db_column='loadingDay', null=True)),
            ],
            options={
                'db_table': 'tbl_deliveryroutes',
                'managed': True,
            },
        ),
    ]
