# Generated by Django 2.0.5 on 2018-10-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0002_auto_20181004_1438'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='highriskpackinglist',
            table='tbl_highriskpackinglist',
        ),
    ]
