# Generated by Django 2.0.5 on 2019-02-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0002_productlist_rankingingroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='rankingInGroup',
        ),
    ]
