# Generated by Django 2.0.5 on 2018-06-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0002_packaging_tbldeliveryroutes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='packaging',
        ),
    ]
