# Generated by Django 2.0.5 on 2018-10-11 08:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrDatabaseModels', '0002_auto_20181009_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_column='year', default=2018)),
                ('week', models.IntegerField(db_column='week', default=1)),
                ('weekDay', models.IntegerField(db_column='weekDay', default=1)),
                ('shift', models.CharField(db_column='shift', default='A', max_length=1)),
                ('shortDate', models.DateField(db_column='shortDate', default=datetime.date.today)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True)),
                ('time', models.ForeignKey(db_column='time', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.StockTakingTimes')),
            ],
            options={
                'db_table': 'tbl_timestamp',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='highriskpackinglist',
            name='id',
        ),
        migrations.RemoveField(
            model_name='processedstockamounts',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='processedstockamounts',
            name='time',
        ),
        migrations.RemoveField(
            model_name='processedstockamounts',
            name='week',
        ),
        migrations.RemoveField(
            model_name='processedstockamounts',
            name='weekDay',
        ),
        migrations.RemoveField(
            model_name='processedstockamounts',
            name='year',
        ),
        migrations.AddField(
            model_name='highriskpackinglist',
            name='user',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processedstockamounts',
            name='user',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productlist',
            name='user',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='highriskpackinglist',
            name='productCode',
            field=models.OneToOneField(db_column='productCode', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mrDatabaseModels.Productlist'),
        ),
    ]
