# Generated by Django 2.0.5 on 2018-06-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0003_remove_productlist_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Packaging'),
        ),
    ]
