# Generated by Django 2.0.5 on 2018-10-12 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0003_auto_20181011_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedstockamounts',
            name='time',
            field=models.ForeignKey(db_column='time', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.StockTakingTimes'),
        ),
        migrations.AddField(
            model_name='processedstockamounts',
            name='timeStampID',
            field=models.ForeignKey(db_column='timeStampID', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.TimeStamp'),
        ),
        migrations.AlterField(
            model_name='processedstockamounts',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, db_column='dateCreated', null=True),
        ),
        migrations.AlterField(
            model_name='processedstockamounts',
            name='user',
            field=models.ForeignKey(db_column='user', default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
