# Generated by Django 2.0.5 on 2018-06-05 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0004_productlist_packaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_productbrands',
                'managed': True,
            },
        ),
    ]
