# Generated by Django 2.0.5 on 2019-02-28 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0004_productlist_rankingingroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBatchNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchMRid', models.CharField(db_column='batchMRid', max_length=255, unique=True)),
                ('cleared', models.BooleanField(db_column='cleared', default=True)),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist')),
            ],
            options={
                'db_table': 'tbl_productbatchnumbers',
                'ordering': ['batchMRid'],
                'managed': True,
            },
        ),
    ]
