# Generated by Django 2.0.5 on 2018-10-12 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0004_auto_20181012_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemDescription', models.CharField(db_column='itemDescription', max_length=10)),
                ('colorCode', models.CharField(db_column='colorCode', max_length=100)),
            ],
            options={
                'db_table': 'tbl_colorcodes',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='batchgroups',
            name='batchname',
            field=models.CharField(db_column='batchName', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='batchgroups',
            name='batchColor',
            field=models.ForeignKey(blank=True, db_column='batchColor', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.ColorCodes'),
        ),
    ]
