# Generated by Django 2.0.5 on 2018-10-12 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0005_auto_20181012_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasuringUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitAmount', models.IntegerField(db_column='unitAmount')),
                ('measuringUnit', models.CharField(db_column='measuringUnit', max_length=10)),
                ('unitDescription', models.CharField(db_column='unitDescription', max_length=10)),
                ('unitColor', models.ForeignKey(blank=True, db_column='unitColor', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.ColorCodes')),
            ],
            options={
                'db_table': 'tbl_measuringunits',
                'managed': True,
            },
        ),
    ]
