# Generated by Django 2.0.5 on 2019-03-01 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0005_productbatchnumbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbatchnumbers',
            name='productid',
        ),
    ]
