# Generated by Django 2.0.5 on 2019-03-01 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0006_remove_productbatchnumbers_productid'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchMRid', models.CharField(db_column='batchMRid', max_length=255, unique=True)),
                ('cleared', models.BooleanField(db_column='cleared', default=True)),
            ],
            options={
                'db_table': 'tbl_batchnumbers',
                'ordering': ['batchMRid'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductBatchNumbersJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchGroup', models.ForeignKey(db_column='batchGroup', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Batchgroups')),
                ('batchNumbers', models.ForeignKey(db_column='batchNumbers', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.BatchNumbers')),
            ],
            options={
                'db_table': 'tbl_productbatchnumbersjunction',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='ProductBatchNumbers',
        ),
        migrations.AddField(
            model_name='batchnumbers',
            name='batchGroup',
            field=models.ManyToManyField(through='mrDatabaseModels.ProductBatchNumbersJunction', to='mrDatabaseModels.Batchgroups'),
        ),
    ]
