# Generated by Django 2.0.5 on 2018-07-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0007_stocktakingtimes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTakingTimes',
        ),
    ]
