# Generated by Django 2.0.5 on 2019-03-01 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrDatabaseModels', '0007_auto_20190301_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatriteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, db_column='batchranking', null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('batchNumberJunctionid', models.ForeignKey(db_column='batchNumberJunctionid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.ProductBatchNumbersJunction')),
                ('productid', models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist')),
                ('userid', models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_meatritestock',
                'managed': True,
            },
        ),
    ]
