# Generated by Django 2.0.5 on 2019-03-01 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0008_meatritestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meatritestock',
            name='batchNumberJunctionid',
        ),
        migrations.RemoveField(
            model_name='meatritestock',
            name='productid',
        ),
        migrations.RemoveField(
            model_name='meatritestock',
            name='userid',
        ),
        migrations.DeleteModel(
            name='MeatriteStock',
        ),
    ]
