# Generated by Django 2.0.5 on 2018-10-12 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0008_auto_20181012_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlist',
            name='unitweight',
        ),
    ]
