# Generated by Django 2.0.5 on 2018-07-02 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0009_stocktakingtimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedStockAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=255, unique=True)),
                ('prodName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist', unique=True)),
            ],
            options={
                'db_table': 'tbl_processedStockAmounts',
                'managed': True,
            },
        ),
    ]
