# Generated by Django 2.0.5 on 2018-10-12 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0009_remove_productlist_unitweight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='unitweight',
            field=models.ForeignKey(blank=True, db_column='unitweight', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.MeasuringUnits'),
        ),
    ]
