# Generated by Django 2.0.5 on 2019-08-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0010_meatritestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='packaging',
            name='packaging_weight',
            field=models.FloatField(blank=True, db_column='packaging_weight', null=True),
        ),
        migrations.AddField(
            model_name='productlist',
            name='packagingShipping',
            field=models.ForeignKey(blank=True, db_column='packagingShipping', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='package_packagingShipping', to='mrDatabaseModels.Packaging'),
        ),
    ]
