# Generated by Django 2.0.5 on 2018-10-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0010_productlist_unitweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='batchgroup',
            field=models.ForeignKey(db_column='batchgroup', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Batchgroups'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='batchranking',
            field=models.IntegerField(blank=True, db_column='batchranking', null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='brand',
            field=models.ForeignKey(blank=True, db_column='brand', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.ProductBrands'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='packageweight',
            field=models.FloatField(blank=True, db_column='packageweight', null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='packaging',
            field=models.ForeignKey(blank=True, db_column='packaging', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Packaging'),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='proddescription',
            field=models.CharField(blank=True, db_column='proddescription', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='productid',
            field=models.CharField(db_column='productid', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='productonhold',
            field=models.BooleanField(db_column='productonhold', default=False),
        ),
        migrations.AlterField(
            model_name='productlist',
            name='user',
            field=models.ForeignKey(db_column='user', default=23, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
