# Generated by Django 2.0.5 on 2018-10-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0011_auto_20181012_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringunits',
            name='unitAmount',
            field=models.DecimalField(db_column='unitAmount', decimal_places=3, max_digits=10),
        ),
    ]
