# Generated by Django 2.0.5 on 2018-07-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0011_auto_20180702_1114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packaging',
            old_name='packagingType',
            new_name='packaging_type',
        ),
    ]
