# Generated by Django 2.0.5 on 2019-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0011_packaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='unitsPerMaxShippingWeight',
            field=models.IntegerField(blank=True, db_column='unitsPerMaxShippingWeight', null=True),
        ),
    ]
