# Generated by Django 2.0.5 on 2018-10-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0012_auto_20181012_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedstockamounts',
            name='prodContainer',
            field=models.ForeignKey(db_column='prodContainer', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productcontainers'),
        ),
    ]
