# Generated by Django 2.0.5 on 2018-07-06 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0012_auto_20180703_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedstockamounts',
            name='prodName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod', to='mrDatabaseModels.Productlist'),
        ),
    ]
