# Generated by Django 2.0.5 on 2018-07-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0013_auto_20180706_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedstockamounts',
            name='amount',
            field=models.CharField(max_length=255),
        ),
    ]
