# Generated by Django 2.0.5 on 2018-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0014_auto_20181017_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(blank=True, max_length=255, null=True)),
                ('imageDescription', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_image',
                'managed': True,
            },
        ),
        migrations.AlterModelOptions(
            name='packaging',
            options={},
        ),
        migrations.AlterField(
            model_name='colorcodes',
            name='colorCode',
            field=models.CharField(db_column='colorCode', max_length=201),
        ),
        migrations.AlterModelTable(
            name='packaging',
            table=None,
        ),
    ]
