# Generated by Django 2.0.5 on 2018-07-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0015_auto_20180709_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='productid',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
