# Generated by Django 2.0.5 on 2018-10-18 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0015_auto_20181018_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontainers',
            name='image',
            field=models.ForeignKey(blank=True, db_column='image', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Image'),
        ),
    ]
