# Generated by Django 2.0.5 on 2018-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0016_auto_20180709_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='productonhold',
            field=models.BooleanField(default=False),
        ),
    ]
