# Generated by Django 2.0.5 on 2018-10-18 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0016_productcontainers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packaging',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='packaging',
            table='tbl_packaging',
        ),
    ]
