# Generated by Django 2.0.5 on 2018-10-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0017_auto_20181018_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrands',
            name='brandSmallImage',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
