# Generated by Django 2.0.5 on 2018-10-18 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0018_productbrands_brandsmallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='measuringunits',
            name='unitImage',
            field=models.ForeignKey(blank=True, db_column='unitImage', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Image'),
        ),
    ]
