# Generated by Django 2.0.5 on 2018-07-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0018_auto_20180720_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productcontainernames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containername', models.CharField(blank=True, db_column='groupName', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_productcontainernames',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productcontainers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containernameid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productcontainernames')),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist')),
            ],
            options={
                'db_table': 'tbl_productcontainers',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='productcontainernames',
            name='members',
            field=models.ManyToManyField(through='mrDatabaseModels.Productcontainers', to='mrDatabaseModels.Productlist'),
        ),
    ]
