# Generated by Django 2.0.5 on 2018-10-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0019_measuringunits_unitimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontainers',
            name='filterCatagory',
            field=models.ForeignKey(blank=True, db_column='filterCatagory', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Factoryarea'),
        ),
    ]
