# Generated by Django 2.0.5 on 2018-10-22 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0020_productcontainers_filtercatagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontainers',
            name='factoryCatagory',
            field=models.ForeignKey(blank=True, db_column='factoryCatagory', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Factoryarea_factoryCatagory', to='mrDatabaseModels.Factoryarea'),
        ),
    ]
