# Generated by Django 2.0.5 on 2018-10-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0021_productcontainers_factorycatagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factoryarea',
            name='areaRanking',
            field=models.IntegerField(db_column='areaRanking'),
        ),
        migrations.AlterField(
            model_name='factorysubarea',
            name='subAreaRanking',
            field=models.IntegerField(db_column='subAreaRanking'),
        ),
    ]
