# Generated by Django 2.0.5 on 2018-07-20 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0021_prosstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prosstock',
            name='prodNameContainer',
            field=models.ForeignKey(db_column='prodNameContainer', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productcontainers'),
        ),
        migrations.AlterField(
            model_name='prosstock',
            name='time',
            field=models.ForeignKey(db_column='time', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.StockTakingTimes'),
        ),
    ]
