# Generated by Django 2.0.5 on 2018-07-23 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0022_auto_20180720_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosstock',
            name='prodNameContainer',
        ),
        migrations.RemoveField(
            model_name='prosstock',
            name='time',
        ),
        migrations.AddField(
            model_name='processedstockamounts',
            name='container',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productcontainernames'),
        ),
        migrations.DeleteModel(
            name='ProsStock',
        ),
    ]
