# Generated by Django 2.0.5 on 2018-11-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0023_auto_20181025_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcontainers',
            name='factoryRanking',
            field=models.IntegerField(blank=True, db_column='factoryranking', null=True),
        ),
    ]
