# Generated by Django 2.0.5 on 2018-08-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0023_auto_20180723_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='stocktakegroup',
            field=models.ForeignKey(db_column='stocktakegroup', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stocktakegroup', to='mrDatabaseModels.Batchgroups'),
        ),
    ]
