# Generated by Django 2.0.5 on 2018-11-19 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0024_auto_20181108_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOfTheWeek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekDayNames', models.CharField(db_column='weekDayNames', max_length=100, unique=True)),
                ('weekDayNumber', models.IntegerField(db_column='weekDayNumber', unique=True)),
                ('weekDayRanking', models.IntegerField(db_column='weekDayRanking', unique=True)),
            ],
            options={
                'db_table': 'tbl_daysoftheweek',
                'managed': True,
            },
        ),
    ]
