# Generated by Django 2.0.5 on 2018-08-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0024_productlist_stocktakegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcontainers',
            name='deleteContainerAmount',
            field=models.BooleanField(default=True),
        ),
    ]
