# Generated by Django 2.0.5 on 2018-11-19 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0025_auto_20181119_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='weekDay3',
            field=models.ForeignKey(db_column='weekDay3', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DaysOfTheWeek'),
        ),
    ]
