# Generated by Django 2.0.5 on 2018-08-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0025_productcontainers_deletecontaineramount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productlist',
            options={'managed': True, 'ordering': ['productid']},
        ),
        migrations.AlterField(
            model_name='stocktakingtimes',
            name='times',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
