# Generated by Django 2.0.5 on 2018-09-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0026_auto_20180830_0726'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighRiskPackingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentStock', models.IntegerField(db_column='currentStock')),
                ('stockNeeded', models.IntegerField(db_column='stockNeeded')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('productCode', models.ForeignKey(db_column='productCode', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist')),
            ],
            options={
                'db_table': 'tbl_highRiskPackingList',
                'managed': True,
            },
        ),
    ]
