# Generated by Django 2.0.5 on 2018-11-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0026_timestamp_weekday3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='weekDay3',
        ),
    ]
