# Generated by Django 2.0.5 on 2018-09-10 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0027_highriskpackinglist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highriskpackinglist',
            name='created',
        ),
        migrations.RemoveField(
            model_name='highriskpackinglist',
            name='last_modified',
        ),
    ]
