# Generated by Django 2.0.5 on 2018-11-19 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0027_remove_timestamp_weekday3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='weekDay',
            field=models.ForeignKey(db_column='weekDay', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DaysOfTheWeek'),
        ),
    ]
