# Generated by Django 2.0.5 on 2018-11-20 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0028_auto_20181119_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRoutes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routeName', models.CharField(db_column='routeName', max_length=255, unique=True)),
                ('loadingDay', models.ForeignKey(db_column='loadingDay', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.DaysOfTheWeek')),
            ],
            options={
                'db_table': 'tbl_deliveryroutes',
                'managed': True,
            },
        ),
    ]
