# Generated by Django 2.0.5 on 2018-09-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0028_auto_20180910_0847'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='highriskpackinglist',
            options={'managed': True, 'ordering': ['productCode']},
        ),
        migrations.AlterField(
            model_name='highriskpackinglist',
            name='productCode',
            field=models.OneToOneField(db_column='productCode', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist'),
        ),
    ]
