# Generated by Django 2.0.5 on 2018-11-21 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0029_deliveryroutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedstockamounts',
            name='amount',
            field=models.CharField(max_length=10),
        ),
    ]
