# Generated by Django 2.0.5 on 2018-09-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0029_auto_20180911_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedstockamounts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
