# Generated by Django 2.0.5 on 2018-11-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0030_auto_20181121_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='brandImage',
            field=models.ForeignKey(blank=True, db_column='brandImage', default=19, null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Image'),
        ),
    ]
