# Generated by Django 2.0.5 on 2018-09-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0031_auto_20180911_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchgroups',
            name='packingListRanking',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
