# Generated by Django 2.0.5 on 2018-11-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0031_productlist_brandimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktakingtimes',
            name='selectiveDelete',
            field=models.BooleanField(db_column='selectiveDelete', default=False),
        ),
    ]
