# Generated by Django 2.0.5 on 2018-09-11 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0032_batchgroups_packinglistranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlist',
            name='packlistgroup',
            field=models.ForeignKey(db_column='packlistgroup', default=20, on_delete=django.db.models.deletion.CASCADE, related_name='packlistgroup', to='mrDatabaseModels.Batchgroups'),
        ),
    ]
