# Generated by Django 2.0.5 on 2019-01-11 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrDatabaseModels', '0032_stocktakingtimes_selectivedelete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shiftName', models.CharField(db_column='shiftName', max_length=100, unique=True)),
                ('shiftSuperVisor', models.ForeignKey(blank=True, db_column='shiftSuperVisor', default=23, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_shifts',
                'managed': True,
            },
        ),
    ]
