# Generated by Django 2.0.5 on 2019-01-11 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0033_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='timestamp',
            name='newShift',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Shifts'),
        ),
    ]
