# Generated by Django 2.0.5 on 2018-10-03 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0033_productlist_packlistgroup'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='highriskpackinglist',
            table='tbl_highriskpackingList',
        ),
        migrations.AlterModelTable(
            name='processedstockamounts',
            table='tbl_processedstockamounts',
        ),
        migrations.AlterModelTable(
            name='stocktakingtimes',
            table='tbl_stocktakingtimes',
        ),
    ]
