# Generated by Django 2.0.5 on 2019-01-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    def link_shifts(apps, schema_editor):
        TimeStamp = apps.get_model('mrDatabaseModels', 'TimeStamp')
        Shifts = apps.get_model('mrDatabaseModels', 'Shifts')
        for timestamp in TimeStamp.objects.all():
            shift, created = Shifts.objects.get_or_create(shiftName=timestamp.shift)
            timestamp.newShift = shift
            timestamp.save()

    dependencies = [
        ('mrDatabaseModels', '0034_timestamp_newshift'),
    ]

    operations = [
         migrations.RunPython(link_shifts),
    ]

    # operations = [
    #     def link_shifts(apps, schema_editor):
    #         TimeStamp = apps.get_model('mrDatabaseModels', 'TimeStamp')
    #         Shifts = apps.get_model('mrDatabaseModels', 'Shifts')
    #         for timestamp in TimeStamp.objects.all():
    #             shift, created = Shifts.objects.get_or_create(name=timestamp.shift)
    #             timestamp.newShift = shift
    #             timestamp.save()
    # ]

# def link_artists(apps, schema_editor):
#     Album = apps.get_model('discography', 'Album')
#     Artist = apps.get_model('discography', 'Artist')
#     for album in Album.objects.all():
#         artist, created = Artist.objects.get_or_create(name=album.artist)
#         album.artist_link = artist
#         album.save()