# Generated by Django 2.0.5 on 2018-10-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0034_auto_20181003_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedstockamounts',
            name='container',
            field=models.ForeignKey(db_column='container', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productcontainernames'),
        ),
        migrations.AlterField(
            model_name='processedstockamounts',
            name='prodName',
            field=models.ForeignKey(db_column='prodName', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist'),
        ),
        migrations.AlterField(
            model_name='processedstockamounts',
            name='time',
            field=models.ForeignKey(db_column='time', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.StockTakingTimes'),
        ),
    ]
