# Generated by Django 2.0.5 on 2019-01-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0035_transfer_shifts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timestamp',
            name='shift',
        ),
    ]
