# Generated by Django 2.0.5 on 2019-01-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0036_remove_timestamp_shift'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timestamp',
            old_name='newShift',
            new_name='shift',
        ),
    ]
