# Generated by Django 2.0.5 on 2019-01-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrDatabaseModels', '0037_auto_20190111_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestamp',
            name='shift',
            field=models.ForeignKey(db_column='shift', null=True, on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Shifts'),
        ),
    ]
