# Generated by Django 2.0.5 on 2019-03-02 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mrDatabaseModels', '0010_meatritestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPPMeatriteStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(db_column='amount')),
                ('lastModified', models.DateTimeField(auto_now=True, db_column='lastModified', null=True)),
                ('batchNumberJunctionid', models.ForeignKey(db_column='batchNumberJunctionid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.ProductBatchNumbersJunction')),
            ],
            options={
                'db_table': 'tbl_hppmeatritestock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HPPProductStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productStatus', models.CharField(db_column='productStatus', max_length=255)),
            ],
            options={
                'db_table': 'tbl_hppproductstatus',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hppmeatritestock',
            name='productStatusid',
            field=models.ForeignKey(db_column='productStatusid', on_delete=django.db.models.deletion.CASCADE, to='mrStock.HPPProductStatus'),
        ),
        migrations.AddField(
            model_name='hppmeatritestock',
            name='productid',
            field=models.ForeignKey(db_column='productid', on_delete=django.db.models.deletion.CASCADE, to='mrDatabaseModels.Productlist'),
        ),
        migrations.AddField(
            model_name='hppmeatritestock',
            name='userid',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
