# Generated by Django 2.0.5 on 2019-02-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('label', models.CharField(db_column='label', max_length=255)),
                ('value', models.CharField(blank=True, db_column='value', max_length=255, null=True)),
                ('disabled', models.BooleanField(db_column='disabled', default=False)),
                ('placeholder', models.CharField(blank=True, db_column='placeholder', max_length=255, null=True)),
                ('ranking', models.IntegerField(blank=True, db_column='ranking', null=True)),
            ],
            options={
                'db_table': 'tbl_formbuilder',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormBuilderExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(db_column='item', max_length=50)),
                ('value', models.IntegerField(blank=True, db_column='value', null=True)),
                ('number', models.IntegerField(blank=True, db_column='number', null=True)),
            ],
            options={
                'db_table': 'tbl_formbuilderextras',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormBuilderExtrasJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formBuilderExtrasID', models.ForeignKey(db_column='formBuilderExtrasID', on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.FormBuilderExtras')),
                ('formBuilderID', models.ForeignKey(db_column='formBuilderID', on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.FormBuilder')),
            ],
            options={
                'db_table': 'tbl_formbuilderextrasjunction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=255)),
            ],
            options={
                'db_table': 'tbl_forms',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SettingsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settingName', models.CharField(db_column='settingName', max_length=255)),
                ('value1', models.CharField(db_column='value1', max_length=255)),
                ('value2', models.CharField(db_column='value2', max_length=255)),
            ],
            options={
                'db_table': 'tbl_settingsdb',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='form',
            field=models.ForeignKey(db_column='form', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.Forms'),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='validation',
            field=models.ManyToManyField(through='mrCoreModels.FormBuilderExtrasJunction', to='mrCoreModels.FormBuilderExtras'),
        ),
    ]
