# Generated by Django 2.0.5 on 2018-11-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdb',
            name='settingName',
            field=models.CharField(db_column='settingName', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
