# Generated by Django 2.0.5 on 2018-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0002_settingsdb_settingname'),
    ]

    operations = [
        migrations.AddField(
            model_name='settingsdb',
            name='value2',
            field=models.CharField(db_column='value2', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
