# Generated by Django 2.0.5 on 2019-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0003_settingsdb_value2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(db_column='formName', max_length=255)),
                ('type', models.CharField(db_column='type', max_length=50)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('label', models.CharField(db_column='label', max_length=255)),
                ('value', models.CharField(blank=True, db_column='value', max_length=255, null=True)),
                ('disabled', models.BooleanField(db_column='disabled', default=False)),
                ('placeholder', models.CharField(blank=True, db_column='placeholder', max_length=255, null=True)),
                ('validation', models.CharField(blank=True, db_column='validation', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_formbuilder',
                'managed': True,
            },
        ),
    ]
