# Generated by Django 2.0.5 on 2019-01-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0004_formbuilder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formName', models.CharField(db_column='formName', max_length=255)),
            ],
            options={
                'db_table': 'tbl_forms',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='formbuilder',
            name='formName',
            field=models.ForeignKey(db_column='formName', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.Forms'),
        ),
    ]
