# Generated by Django 2.0.5 on 2019-01-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0005_auto_20190103_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='formName',
        ),
        migrations.RemoveField(
            model_name='forms',
            name='formName',
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='form',
            field=models.ForeignKey(db_column='form', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.Forms'),
        ),
        migrations.AddField(
            model_name='forms',
            name='name',
            field=models.CharField(db_column='name', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
