# Generated by Django 2.0.5 on 2019-01-04 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0006_auto_20190103_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilderExtras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(db_column='item', max_length=50)),
                ('value', models.CharField(blank=True, db_column='value', max_length=255, null=True)),
                ('form', models.ForeignKey(db_column='form', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.Forms')),
            ],
            options={
                'db_table': 'tbl_formbuilderextras',
                'managed': True,
            },
        ),
    ]
