# Generated by Django 2.0.5 on 2019-01-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0007_formbuilderextras'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilderextras',
            name='formBuilder',
            field=models.ForeignKey(db_column='formBuilder', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.FormBuilder'),
        ),
        migrations.AddField(
            model_name='formbuilderextras',
            name='number',
            field=models.IntegerField(db_column='number', default=1),
            preserve_default=False,
        ),
    ]
