# Generated by Django 2.0.5 on 2019-01-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0008_auto_20190104_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formbuilder',
            name='form',
        ),
        migrations.RemoveField(
            model_name='formbuilderextras',
            name='form',
        ),
    ]
