# Generated by Django 2.0.5 on 2019-01-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0009_auto_20190104_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='form',
            field=models.ForeignKey(db_column='form', default=1, on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.Forms'),
        ),
    ]
