# Generated by Django 2.0.5 on 2019-01-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0010_formbuilder_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBuilderExtrasJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'tbl_formbuilderextrasjunction',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='formbuilderextras',
            name='formBuilder',
        ),
        migrations.RemoveField(
            model_name='formbuilder',
            name='validation',
        ),
        migrations.AlterField(
            model_name='formbuilderextras',
            name='number',
            field=models.IntegerField(blank=True, db_column='number', null=True),
        ),
        migrations.AlterField(
            model_name='formbuilderextras',
            name='value',
            field=models.IntegerField(blank=True, db_column='value', null=True),
        ),
        migrations.AddField(
            model_name='formbuilderextrasjunction',
            name='formBuilderExtrasID',
            field=models.ForeignKey(db_column='formBuilderExtrasID', on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.FormBuilderExtras'),
        ),
        migrations.AddField(
            model_name='formbuilderextrasjunction',
            name='formBuilderID',
            field=models.ForeignKey(db_column='formBuilderID', on_delete=django.db.models.deletion.CASCADE, to='mrCoreModels.FormBuilder'),
        ),
        migrations.AddField(
            model_name='formbuilder',
            name='validation',
            field=models.ManyToManyField(through='mrCoreModels.FormBuilderExtrasJunction', to='mrCoreModels.FormBuilderExtras'),
        ),
    ]
