# Generated by Django 2.0.5 on 2019-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mrCoreModels', '0011_auto_20190104_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='formbuilder',
            name='ranking',
            field=models.IntegerField(blank=True, db_column='ranking', null=True),
        ),
    ]
